name: Build and Deploy

on:
  push:
    branches: [ "prod" ]

jobs:
  build:


    runs-on: self-hosted

    steps:
      -uses: action/checkout@v3
      -name: Use Node.js 20
      uses: action/setup-node@v3.5.0
      with:
        node-version: '20.x'
        cache: 'npm'
      
      -name: Install Dependencies
        run: |
          npm install
          cd client
          npm install
      
      -name: Create Production Build
        run: |
        npm run build
        cd ..

  deploy:

    runs-on: self-hosted
    needs: [build]

    steps:
    - name: Deploy to production
    run: |
    pm2 stop 0
    pm2 start 0
    pm2 save