name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.3.0
      with:
        # DigitalOcean API Token
        token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
        
    - run: echo 'Deployment successful'
